import { it } from 'vitest';
import { writeFileSync } from 'node:fs';
import { COMBATANTS, OFFICIAL, ROSTER, deriveStats, degreeOf, levelDc, type UnitCard } from '../engine/index.js';

// Not a test: a table generator for the action review (docs/plans/action-review.md). Runs only
// when asked, so the ordinary suite never pays for it:
//   MATCHUP="Line Infantry>Kobold Warriors,Line Infantry>Heavy Cavalry" npx vitest run src/tests/matchup.test.ts
// writes docs/plans/matchups.md. With MATCHUP=1 it runs the three standard matchups.

const STANDARD = 'Line Infantry>Kobold Warriors,Line Infantry>Heavy Cavalry,Kobold Warriors>Line Infantry';

const find = (name: string): UnitCard => {
  const c = [...COMBATANTS, ...OFFICIAL, ...ROSTER].find((x) => x.name === name);
  if (!c) throw new Error(`no unit named ${name}`);
  return c;
};

/** Shares of the four degrees, in percent, for d20 + modifier against dc. */
function odds(modifier: number, dc: number) {
  const o = { crit: 0, hit: 0, miss: 0, botch: 0 };
  for (let roll = 1; roll <= 20; roll++) {
    const d = degreeOf(roll, modifier, dc);
    if (d === 'critical-success') o.crit += 5;
    else if (d === 'success') o.hit += 5;
    else if (d === 'failure') o.miss += 5;
    else o.botch += 5;
  }
  return o;
}
const pct = (n: number) => `${Math.round(n)}%`;

function row(a: UnitCard, b: UnitCard) {
  const A = deriveStats(a);
  const B = deriveStats(b);
  const strike = A.strike === null ? null : odds(A.strike, B.defence);
  const volley = A.volley === null ? null : odds(A.volley, B.defence);
  const fort = odds(B.fortitude, levelDc(a.level));
  const will = odds(A.will, levelDc(b.level));
  const lines = [`### ${a.name} (L${a.level}) into ${b.name} (L${b.level})`, ''];
  lines.push(`Strike +${A.strike ?? '—'} · Volley +${A.volley ?? '—'} · Will +${A.will} · level DC ${levelDc(a.level)} — against Defence ${B.defence} · Fortitude +${B.fortitude} · level DC ${levelDc(b.level)}`, '');
  lines.push('| Attack | Crit | Hit | Miss | Crit miss | Wounds expected | Target disorder, save | Target disorder, no save | Attacker disorder on a miss |');
  lines.push('|---|---|---|---|---|---|---|---|---|');
  const saveFail = (fort.miss + fort.botch) / 100;
  const willFail = (will.miss + will.botch) / 100;
  for (const [label, o, repulsed] of [['Fight', strike, true], ['Shoot', volley, false]] as const) {
    if (!o) continue;
    const lands = (o.crit + o.hit) / 100;
    const wounds = (o.crit * 2 + o.hit) / 100;
    lines.push(`| ${label} | ${pct(o.crit)} | ${pct(o.hit)} | ${pct(o.miss)} | ${pct(o.botch)} | ${wounds.toFixed(2)} | ${pct(lands * saveFail * 100)} | ${pct(lands * 100)} | ${repulsed ? pct((1 - lands) * willFail * 100) : '—'} |`);
  }
  lines.push('', `Fortitude save fails ${pct(saveFail * 100)} of the time; the attacker's Will save fails ${pct(willFail * 100)}.`, '');
  return lines.join('\n');
}

it.skipIf(!process.env.MATCHUP)('writes docs/plans/matchups.md', () => {
  const spec = process.env.MATCHUP === '1' ? STANDARD : process.env.MATCHUP!;
  const pairs = spec.split(',').map((p) => p.split('>').map((s) => s.trim()) as [string, string]);
  const out = ['# Matchups', '', `Generated by \`src/tests/matchup.test.ts\` from the roster on ${new Date().toISOString().slice(0, 10)}. One attack, per the rules in force.`, ''];
  for (const [x, y] of pairs) out.push(row(find(x), find(y)));
  writeFileSync('docs/plans/matchups.md', out.join('\n'));
});
