import type { SiegeEngineCard } from './cards.js';

// Generated by scripts/import-engines.mjs from data/siege-weapons/*.json (pf2e-trooper's ORC-scrubbed capture). Edit the JSON, not this file.
export const ENGINES: SiegeEngineCard[] = [
  { name: "Teekdoon", level: 1, kind: 'artillery', launch: 4, reach: 'long', defence: 11 }, // Howl of the Wild
  { name: "Door Ram", level: 2, kind: 'ram', launch: 6, reach: null, defence: 12 }, // Guns & Gears (Remastered)
  { name: "Crossbow Catapult", level: 3, kind: 'artillery', launch: 7, reach: 'long', defence: 13 }, // Battlecry!
  { name: "Flame Bellows", level: 3, kind: 'artillery', launch: 7, reach: 'long', defence: 15 }, // Battlecry!
  { name: "Trapdoor Actuator", level: 3, kind: 'artillery', launch: 8, reach: 'long', defence: 16 }, // Howl of the Wild
  { name: "Falconet", level: 4, kind: 'artillery', launch: 8, reach: 'long', defence: 16 }, // Battlecry!
  { name: "Hwacha", level: 4, kind: 'artillery', launch: 8, reach: 'extreme', defence: 16 }, // Guns & Gears (Remastered)
  { name: "Ribauldequin", level: 4, kind: 'artillery', launch: 8, reach: 'long', defence: 16 }, // Battlecry!
  { name: "Ballista", level: 5, kind: 'artillery', launch: 9, reach: 'long', defence: 17 }, // Guns & Gears (Remastered)
  { name: "Battering Ram", level: 5, kind: 'ram', launch: 10, reach: null, defence: 15 }, // Guns & Gears (Remastered)
  { name: "Bombard", level: 5, kind: 'artillery', launch: 9, reach: 'extreme', defence: 17 }, // Guns & Gears (Remastered)
  { name: "Marking Powder Cannon", level: 5, kind: 'artillery', launch: 9, reach: 'long', defence: 18 }, // Howl of the Wild
  { name: "Pheromone Sprayer", level: 5, kind: 'artillery', launch: 10, reach: 'long', defence: 19 }, // Howl of the Wild
  { name: "Steam Artillery", level: 5, kind: 'artillery', launch: 9, reach: 'close', defence: 16 }, // Battlecry!
  { name: "Wolf Fang", level: 5, kind: 'artillery', launch: 10, reach: 'long', defence: 18 }, // Battlecry!
  { name: "Drilling Ram", level: 6, kind: 'ram', launch: 12, reach: null, defence: 16 }, // Battlecry!
  { name: "Blasting Ram", level: 7, kind: 'ram', launch: 13, reach: null, defence: 17 }, // Guns & Gears (Remastered)
  { name: "Catapult", level: 7, kind: 'artillery', launch: 12, reach: 'extreme', defence: 20 }, // Guns & Gears (Remastered)
  { name: "Harpoon Cannon", level: 7, kind: 'artillery', launch: 12, reach: 'long', defence: 20 }, // Howl of the Wild
  { name: "Kickback Spring", level: 7, kind: 'artillery', launch: 12, reach: 'close', defence: 20 }, // Howl of the Wild
  { name: "Mortar", level: 7, kind: 'artillery', launch: 13, reach: 'long', defence: 20 }, // Guns & Gears (Remastered)
  { name: "Springald", level: 7, kind: 'artillery', launch: 12, reach: 'long', defence: 20 }, // Guns & Gears (Remastered)
  { name: "Arcane Ram", level: 8, kind: 'ram', launch: 14, reach: null, defence: 18 }, // Battlecry!
  { name: "Blob Paste Propulsor", level: 8, kind: 'artillery', launch: 14, reach: 'long', defence: 18 }, // Howl of the Wild
  { name: "Cannon", level: 8, kind: 'artillery', launch: 13, reach: 'extreme', defence: 22 }, // Guns & Gears (Remastered)
  { name: "Firedrake", level: 8, kind: 'artillery', launch: 13, reach: 'long', defence: 22 }, // Guns & Gears (Remastered)
  { name: "Heavy Ballista", level: 8, kind: 'artillery', launch: 13, reach: 'extreme', defence: 22 }, // Guns & Gears (Remastered)
  { name: "Web Launcher", level: 8, kind: 'artillery', launch: 13, reach: 'long', defence: 21 }, // Battlecry!
  { name: "Bolt Emitter", level: 9, kind: 'artillery', launch: 16, reach: 'long', defence: 22 }, // Pathfinder #215: To Blot Out the Sun
  { name: "Heavy Bombard", level: 9, kind: 'artillery', launch: 15, reach: 'extreme', defence: 23 }, // Guns & Gears (Remastered)
  { name: "Lashtail", level: 9, kind: 'artillery', launch: 15, reach: 'long', defence: 23 }, // Howl of the Wild
  { name: "Shatterpult", level: 9, kind: 'artillery', launch: 15, reach: 'extreme', defence: 22 }, // Battlecry!
  { name: "Blessed Onager", level: 10, kind: 'artillery', launch: 16, reach: 'long', defence: 24 }, // Battlecry!
  { name: "Sonic Horn", level: 10, kind: 'artillery', launch: 15, reach: 'extreme', defence: 22 }, // Howl of the Wild
  { name: "Trebuchet", level: 10, kind: 'artillery', launch: 16, reach: 'extreme', defence: 24 }, // Guns & Gears (Remastered)
  { name: "Fiend's Mouth Cannon", level: 11, kind: 'artillery', launch: 17, reach: 'extreme', defence: 26 }, // Guns & Gears (Remastered)
  { name: "Nullifier Sling", level: 11, kind: 'artillery', launch: 17, reach: 'extreme', defence: 25 }, // Battlecry!
  { name: "Seedpod Shooter", level: 11, kind: 'artillery', launch: 17, reach: 'extreme', defence: 26 }, // Howl of the Wild
  { name: "Tar Spitter", level: 11, kind: 'artillery', launch: 17, reach: 'long', defence: 24 }, // Battlecry!
  { name: "Clockwork Ballista", level: 12, kind: 'artillery', launch: 19, reach: 'extreme', defence: 28 }, // Battlecry!
  { name: "Galvanic Sled", level: 12, kind: 'artillery', launch: 19, reach: 'long', defence: 28 }, // Battlecry!
  { name: "Alchemical Springald", level: 13, kind: 'artillery', launch: 20, reach: 'long', defence: 29 }, // Guns & Gears (Remastered)
  { name: "Anesthetizing Jaws", level: 13, kind: 'artillery', launch: 21, reach: 'long', defence: 30 }, // Howl of the Wild
  { name: "Blasting Horn", level: 13, kind: 'artillery', launch: 20, reach: 'long', defence: 29 }, // Battlecry!
  { name: "Cyclonic Cannon", level: 13, kind: 'artillery', launch: 21, reach: 'long', defence: 30 }, // Pathfinder #223: Hell's Destiny
  { name: "Hydraulic Cannon", level: 13, kind: 'artillery', launch: 20, reach: 'extreme', defence: 29 }, // Guns & Gears (Remastered)
  { name: "Mud Maker", level: 13, kind: 'artillery', launch: 20, reach: 'long', defence: 30 }, // Battlecry!
  { name: "Sigilstone Slinger", level: 14, kind: 'artillery', launch: 21, reach: 'extreme', defence: 32 }, // Battlecry!
  { name: "Aquatic Disintegrator", level: 15, kind: 'artillery', launch: 23, reach: 'extreme', defence: 30 }, // Howl of the Wild
  { name: "Burning Glass", level: 15, kind: 'artillery', launch: 23, reach: 'long', defence: 32 }, // Battlecry!
  { name: "Glacial Zephyr", level: 15, kind: 'artillery', launch: 23, reach: 'long', defence: 34 }, // Battlecry!
  { name: "Great Bronze Cannon", level: 15, kind: 'artillery', launch: 23, reach: 'close', defence: 32 }, // Guns & Gears (Remastered)
  { name: "Seismic Amplifier", level: 15, kind: 'artillery', launch: 23, reach: 'extreme', defence: 29 }, // Howl of the Wild
  { name: "Flute Rocket", level: 16, kind: 'artillery', launch: 24, reach: 'extreme', defence: 34 }, // Battlecry!
  { name: "Fleshforged Disgorger", level: 17, kind: 'artillery', launch: 25, reach: 'long', defence: 36 }, // Battlecry!
  { name: "Volley Gun", level: 17, kind: 'artillery', launch: 25, reach: 'long', defence: 36 }, // Battlecry!
  { name: "Long Cannon", level: 18, kind: 'artillery', launch: 27, reach: 'extreme', defence: 38 }, // Battlecry!
  { name: "Corrupted Polyp", level: 19, kind: 'artillery', launch: 28, reach: 'extreme', defence: 38 }, // Battlecry!
  { name: "Fists of Divinity", level: 20, kind: 'artillery', launch: 29, reach: 'long', defence: 40 }, // Battlecry!
];
