import type { UnitCard } from './cards.js';

// Generated by scripts/import-official.mjs from the Pathfinder Second Edition system source (ORC licence). Numbers only.
export const OFFICIAL: UnitCard[] = [
  { name: "Mercenary Squad", level: 2, role: 'skirmisher', pace: false, fear: false, tactics: [], overrides: { strike: 5, volley: 5, reach: 'long', defence: 18, will: 5, perception: 11 } }, // Pathfinder Society Quest #17: Escorting a Mirage
  { name: "Conscript Squad", level: 3, role: 'levy', pace: false, fear: false, tactics: [], overrides: { strike: 7, volley: null, reach: null, defence: 18, will: 6, perception: 8 } }, // Pathfinder NPC Core
  { name: "Goblin Rabble", level: 4, role: 'levy', pace: false, fear: false, tactics: [], overrides: { strike: 8, volley: null, reach: null, defence: 20, will: 8, perception: 11 } }, // Pathfinder Battlecry!
  { name: "Mitflit Vermin Cavalry", level: 4, role: 'cavalry', pace: false, fear: false, tactics: [], overrides: { strike: 8, volley: null, reach: null, defence: 20, will: 11, perception: 14 } }, // Pathfinder Battlecry!
  { name: "Shambler Troop", level: 4, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 8, volley: null, reach: null, defence: 18, will: 9, perception: 7 } }, // Pathfinder Monster Core 2
  { name: "Apprentice Magician Clique", level: 5, role: 'archers', pace: false, fear: false, tactics: [], overrides: { strike: 9, volley: 9, reach: 'long', defence: 21, will: 15, perception: 12 } }, // Pathfinder Battlecry!
  { name: "City Guard Squadron", level: 5, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 9, volley: 9, reach: 'long', defence: 22, will: 11, perception: 12 } }, // Pathfinder NPC Core
  { name: "Orc Raiding Party", level: 5, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 9, volley: 9, reach: 'close', defence: 21, will: 12, perception: 15 } }, // Pathfinder Battlecry!
  { name: "Velociraptor Pack", level: 5, role: 'monster', pace: true, fear: false, tactics: [], overrides: { strike: 9, volley: null, reach: null, defence: 21, will: 8, perception: 12 } }, // Pathfinder Monster Core 2
  { name: "Hobgoblin Battalion", level: 6, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 11, volley: 11, reach: 'long', defence: 23, will: 14, perception: 15 } }, // Pathfinder NPC Core
  { name: "Phalanx Formation", level: 6, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 11, volley: 11, reach: 'close', defence: 23, will: 14, perception: 16 } }, // Pathfinder NPC Core
  { name: "Qadiran Camel Corps", level: 6, role: 'cavalry', pace: true, fear: false, tactics: [], overrides: { strike: 11, volley: 11, reach: 'close', defence: 23, will: 11, perception: 14 } }, // Pathfinder Battlecry!
  { name: "Scamp Inferno", level: 6, role: 'monster', pace: true, fear: false, tactics: [], overrides: { strike: 11, volley: null, reach: null, defence: 23, will: 14, perception: 14 } }, // Pathfinder Battlecry!
  { name: "Aurochs Herd", level: 7, role: 'monster', pace: false, fear: false, tactics: [], overrides: { strike: 12, volley: null, reach: null, defence: 24, will: 12, perception: 12 } }, // Pathfinder #208: Hoof, Cinder, and Storm
  { name: "Bandit Gang", level: 7, role: 'skirmisher', pace: false, fear: false, tactics: [], overrides: { strike: 12, volley: 12, reach: 'close', defence: 24, will: 13, perception: 15 } }, // Pathfinder NPC Core
  { name: "Gnome Cannon Corps", level: 7, role: 'siege', pace: false, fear: false, tactics: [], overrides: { strike: null, volley: 12, reach: 'extreme', defence: 24, will: 18, perception: 15 } }, // Pathfinder Battlecry!
  { name: "Ghostly Mob", level: 8, role: 'monster', pace: false, fear: false, tactics: [], overrides: { strike: 13, volley: null, reach: null, defence: 25, will: 18, perception: 16 } }, // Pathfinder Monster Core 2
  { name: "Hell Hound Pack", level: 8, role: 'monster', pace: true, fear: false, tactics: [], overrides: { strike: 13, volley: null, reach: null, defence: 26, will: 14, perception: 16 } }, // Pathfinder Battlecry!
  { name: "Hellknight Cavalry Brigade", level: 8, role: 'cavalry', pace: true, fear: false, tactics: [], overrides: { strike: 13, volley: 13, reach: 'long', defence: 27, will: 16, perception: 16 } }, // Pathfinder NPC Core
  { name: "Woodland Scouts", level: 8, role: 'archers', pace: true, fear: false, tactics: [], overrides: { strike: 14, volley: 14, reach: 'long', defence: 27, will: 16, perception: 18 } }, // Pathfinder NPC Core
  { name: "Gargoyle Wing", level: 9, role: 'monster', pace: true, fear: false, tactics: [], overrides: { strike: 18, volley: null, reach: null, defence: 28, will: 17, perception: 18 } }, // Pathfinder Battlecry!
  { name: "Hobgoblin Veteran Regiment", level: 9, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 15, volley: 15, reach: 'close', defence: 27, will: 19, perception: 18 } }, // Pathfinder Battlecry!
  { name: "Wight Battalion", level: 9, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 15, volley: null, reach: null, defence: 27, will: 18, perception: 18 } }, // Pathfinder Battlecry!
  { name: "Dwarf Longshot Squad", level: 10, role: 'archers', pace: false, fear: false, tactics: [], overrides: { strike: 16, volley: 16, reach: 'long', defence: 29, will: 16, perception: 22 } }, // Pathfinder Battlecry!
  { name: "Redcap Brigade", level: 10, role: 'skirmisher', pace: true, fear: false, tactics: [], overrides: { strike: 16, volley: null, reach: null, defence: 29, will: 17, perception: 19 } }, // Pathfinder Battlecry!
  { name: "Clockwork Infantry", level: 11, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 17, volley: null, reach: null, defence: 30, will: 18, perception: 21 } }, // Pathfinder Battlecry!
  { name: "Viking Guard", level: 11, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 17, volley: null, reach: null, defence: 30, will: 18, perception: 21 } }, // Pathfinder Battlecry!
  { name: "Angelic Chorus", level: 12, role: 'monster', pace: true, fear: false, tactics: [], overrides: { strike: 19, volley: 19, reach: 'long', defence: 32, will: 25, perception: 22 } }, // Pathfinder Battlecry!
  { name: "Archer Regiment", level: 12, role: 'archers', pace: false, fear: false, tactics: [], overrides: { strike: 19, volley: 19, reach: 'extreme', defence: 32, will: 22, perception: 22 } }, // Pathfinder Battlecry!
  { name: "Drake Flight", level: 13, role: 'monster', pace: true, fear: false, tactics: [], overrides: { strike: 20, volley: 20, reach: 'long', defence: 33, will: 20, perception: 23 } }, // Pathfinder Battlecry!
  { name: "First-Class Infantry", level: 13, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 19, volley: 20, reach: 'long', defence: 33, will: 20, perception: 23 } }, // Pathfinder Battlecry!
  { name: "Terra-Cotta Garrison", level: 13, role: 'infantry', pace: false, fear: false, tactics: [], overrides: { strike: 20, volley: 15, reach: 'long', defence: 27, will: 20, perception: 22 } }, // Pathfinder Bestiary 3
  { name: "Xulgath Dinosaur Cavalry", level: 13, role: 'cavalry', pace: true, fear: false, tactics: [], overrides: { strike: 20, volley: 20, reach: 'close', defence: 33, will: 23, perception: 23 } }, // Pathfinder Battlecry!
  { name: "Monk Cadre", level: 14, role: 'skirmisher', pace: true, fear: false, tactics: [], overrides: { strike: 21, volley: 21, reach: 'close', defence: 35, will: 25, perception: 28 } }, // Pathfinder Battlecry!
  { name: "Einherji Host", level: 15, role: 'infantry', pace: true, fear: false, tactics: [], overrides: { strike: 26, volley: null, reach: null, defence: 35, will: 25, perception: 22 } }, // Pathfinder Adventure: Prey for Death
  { name: "Archon Bastion", level: 16, role: 'infantry', pace: true, fear: false, tactics: [], overrides: { strike: 24, volley: 24, reach: 'close', defence: 37, will: 28, perception: 30 } }, // Pathfinder Battlecry!
  { name: "Valkyrie Tempest", level: 17, role: 'monster', pace: true, fear: false, tactics: [], overrides: { strike: 28, volley: null, reach: null, defence: 37, will: 23, perception: 28 } }, // Pathfinder Adventure: Prey for Death
  { name: "Lich Legion", level: 18, role: 'monster', pace: false, fear: true, tactics: [], overrides: { strike: 27, volley: null, reach: null, defence: 41, will: 33, perception: 30 } }, // Pathfinder Battlecry!
  { name: "Angelic Host", level: 20, role: 'monster', pace: true, fear: false, tactics: [], overrides: { strike: 29, volley: 29, reach: 'close', defence: 44, will: 36, perception: 33 } }, // Pathfinder Adventure Path: Hell's Destiny
];
