import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { actionsOf, casterOf, signalsOf } from './troop-signals.mjs';
import { spellcastingOf } from '../src/adapters/pf2e/spellcasting.ts';

const dir = new URL('../data/troops/', import.meta.url);
const files = readdirSync(dir).filter((f) => f.endsWith('.json')).sort();

const dc = (html) => Number(/dc:(\d+)/.exec(html ?? '')?.[1] ?? NaN);
const feet = (html) => Number(/within (\d+) feet/.exec(html ?? '')?.[1] ?? NaN);
// Extreme is reserved for siege engines (see BANDS in types.ts) — a troop's own Salvo attack
// never derives it, however far its range increment runs.
const reachOf = (html) => {
  const ft = feet(html);
  return Number.isNaN(ft) ? null : ft <= 60 ? 'short' : ft <= 120 ? 'medium' : 'long';
};

function role(d) {
  return d.flags?.['pf2e-reignmaker']?.creatureData?.armyType === 'cavalry' ? 'cavalry' : 'infantry';
}

const cards = files.map((f) => {
  const d = JSON.parse(readFileSync(join(dir.pathname, f), 'utf8'));
  const s = d.system;
  const battle = d.items.find((it) => it.name.includes('[Battle]'));
  const salvo = d.items.find((it) => it.name.includes('[Salvo]'));
  const battleDc = dc(battle?.system.description.value);
  if (Number.isNaN(battleDc)) throw new Error(`${f}: no Battle DC`);
  const salvoDc = salvo ? dc(salvo.system.description.value) : NaN;
  const reach = salvo ? reachOf(salvo.system.description.value) : null;
  const actions = actionsOf(d);
  const fly = (s.attributes.speed.otherSpeeds ?? []).some((o) => o.type === 'fly');
  const { tradition, ...spellStats } = spellcastingOf(d.items);
  return {
    slug: f.replace(/\.json$/, ''),
    name: d.name,
    level: s.details.level.value,
    role: role(d),
    pace: fly || s.attributes.speed.value >= 30,
    fear: false,
    caster: casterOf(d, actions),
    tradition,
    signals: signalsOf(actions),
    tactics: [],
    sheet: {
      ac: s.attributes.ac.value,
      hp: s.attributes.hp.max,
      battleDc,
      salvoDc: salvo ? salvoDc : null,
      salvoFeet: salvo ? feet(salvo.system.description.value) : null,
      fortitude: s.saves.fortitude.value,
      reflex: s.saves.reflex.value,
      will: s.saves.will.value,
      perception: s.perception?.mod ?? s.attributes.perception?.value ?? 0,
      speed: s.attributes.speed.value,
      fly,
      battleName: battle.name,
      ...(salvo ? { salvoName: salvo.name } : {}),
      ...spellStats,
    },
    overrides: {
      strike: battleDc - 10,
      volley: salvo ? salvoDc - 10 : null,
      reach,
      defence: s.attributes.ac.value,
      will: s.saves.will.value,
      perception: s.perception?.mod ?? s.attributes.perception?.value ?? 0,
    },
  };
}).sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));

const body = cards.map((c) => {
  const o = c.overrides;
  const reach = o.reach ? `'${o.reach}'` : 'null';
  return `  { name: ${JSON.stringify(c.name)}, level: ${c.level}, role: '${c.role}', salvo: ${reach}, pace: ${c.pace}, fear: false, caster: ${c.caster}, ${c.tradition ? `tradition: '${c.tradition}', ` : ''}signals: ${JSON.stringify(c.signals)}, tactics: [], sheet: ${JSON.stringify(c.sheet)}, overrides: { strike: ${o.strike}, volley: ${o.volley}, reach: ${reach}, defence: ${o.defence}, will: ${o.will}, perception: ${o.perception} } },`;
}).join('\n');

writeFileSync(new URL('../src/engine/combatants.ts', import.meta.url),
`import type { UnitCard } from './cards.js';

// Generated by scripts/import-troops.mjs from data/troops/*.json. Edit the JSON, not this file.
export const COMBATANTS: UnitCard[] = [
${body}
];
`);
console.log(`${cards.length} combatants written`);
