import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = new URL('../data/siege-weapons/', import.meta.url);
const LEVEL_DC = [14, 15, 16, 18, 19, 20, 22, 23, 24, 26, 27, 28, 30, 31, 32, 34, 35, 36, 38, 39, 40];

const engines = readdirSync(dir).filter((f) => f.endsWith('.json')).sort().map((f) => {
  const d = JSON.parse(readFileSync(join(dir.pathname, f), 'utf8'));
  const text = d.text ?? '';
  const launch = /(?:Launch|Fire)[^]*?$/.exec(text)?.[0] ?? '';
  const ram = (/\bRam\b/.test(text) && !/Launch/.test(text)) || d.name === 'Wolf Fang';
  const rawLoad = ({ Single: 1, Two: 2, Three: 3 }[/\bLoad (Single|Two|Three) Actions?/.exec(text)?.[1]] ?? 1) * Number(/\bLoad[^]*?(\d+) times?/.exec(text)?.[1] ?? 1);
  const noLoad = ram || d.name === 'Bolt Emitter';
  const dc = Number(/DC (\d+) (?:basic )?(?:Reflex|Fortitude|Will)/.exec(launch)?.[1] ?? NaN);
  const rangeFt = Number(/range increment (\d+) feet/.exec(text)?.[1] ?? NaN);
  const level = d.level ?? 1;
  return {
    name: d.name,
    level,
    kind: ram ? 'ram' : 'artillery',
    launch: (Number.isNaN(dc) ? LEVEL_DC[Math.min(20, level)] : dc) - 10,
    // Unlike a troop's Salvo, an engine's reach may land on extreme — that band is what
    // siege equipment is for.
    reach: ram ? null : Number.isNaN(rangeFt) ? 'medium' : rangeFt <= 60 ? 'short' : rangeFt <= 120 ? 'medium' : 'extreme',
    defence: d.defenses?.ac ?? 10 + level,
    // Thirty sheet feet become one 10-foot battlefield hex, as for troops.
    // Engines retain half-hex pacing so slower equipment costs two Moves per hex.
    // Portable equipment travels at its crew's pace; mounted equipment needs a listed speed.
    speed: d.name === 'Wolf Fang' ? 5 : /portable/.test(d.usage ?? '') ? null : /tracks/.test(d.speed ?? '') ? 0 : Math.ceil(Number(/^(\d+)/.exec(d.speed ?? '')?.[1] ?? 0) / 15) * 5,
    loadCost: noLoad ? 0 : rawLoad <= 4 ? 1 : rawLoad <= 8 ? 2 : 3,
    loadSteps: noLoad ? 0 : 1,

    source: d.source?.book ?? '',
  };
}).sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));

const body = engines.map((e) =>
  `  { name: ${JSON.stringify(e.name)}, level: ${e.level}, kind: '${e.kind}', launch: ${e.launch}, reach: ${e.reach ? `'${e.reach}'` : 'null'}, defence: ${e.defence}, speed: ${e.speed}, loadCost: ${e.loadCost}, loadSteps: ${e.loadSteps} }, // ${e.source}`).join('\n');

writeFileSync(new URL('../src/engine/engines.ts', import.meta.url),
`import type { SiegeEngineCard } from './cards.js';

// Generated by scripts/import-engines.mjs from data/siege-weapons/*.json (pf2e-trooper's ORC-scrubbed capture). Edit the JSON, not this file.
export const ENGINES: SiegeEngineCard[] = [
${body}
];
`);
console.log(`${engines.length} engines written`);
