import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = new URL('../data/siege-weapons/', import.meta.url);
const LEVEL_DC = [14, 15, 16, 18, 19, 20, 22, 23, 24, 26, 27, 28, 30, 31, 32, 34, 35, 36, 38, 39, 40];

const engines = readdirSync(dir).filter((f) => f.endsWith('.json')).sort().map((f) => {
  const d = JSON.parse(readFileSync(join(dir.pathname, f), 'utf8'));
  const text = d.text ?? '';
  const launch = /Launch[^]*?$/.exec(text)?.[0] ?? '';
  const ram = /\bRam\b/.test(text) && !/Launch/.test(text);
  const dc = Number(/DC (\d+) (?:basic )?(?:Reflex|Fortitude|Will)/.exec(launch)?.[1] ?? NaN);
  const rangeFt = Number(/range increment (\d+) feet/.exec(text)?.[1] ?? NaN);
  const level = d.level ?? 1;
  return {
    name: d.name,
    level,
    kind: ram ? 'ram' : 'artillery',
    launch: (Number.isNaN(dc) ? LEVEL_DC[Math.min(20, level)] : dc) - 10,
    // Unlike a troop's Salvo, an engine's reach may land on extreme — that band is what
    // siege equipment is for.
    reach: ram ? null : Number.isNaN(rangeFt) ? 'medium' : rangeFt <= 60 ? 'short' : rangeFt <= 120 ? 'medium' : 'extreme',
    defence: d.defenses?.ac ?? 10 + level,
    source: d.source?.book ?? '',
  };
}).sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));

const body = engines.map((e) =>
  `  { name: ${JSON.stringify(e.name)}, level: ${e.level}, kind: '${e.kind}', launch: ${e.launch}, reach: ${e.reach ? `'${e.reach}'` : 'null'}, defence: ${e.defence} }, // ${e.source}`).join('\n');

writeFileSync(new URL('../src/engine/engines.ts', import.meta.url),
`import type { SiegeEngineCard } from './cards.js';

// Generated by scripts/import-engines.mjs from data/siege-weapons/*.json (pf2e-trooper's ORC-scrubbed capture). Edit the JSON, not this file.
export const ENGINES: SiegeEngineCard[] = [
${body}
];
`);
console.log(`${engines.length} engines written`);
