import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = new URL('../data/troops/', import.meta.url);
const files = readdirSync(dir).filter((f) => f.endsWith('.json')).sort();

const dc = (html) => Number(/dc:(\d+)/.exec(html ?? '')?.[1] ?? NaN);
const reachOf = (html) => {
  const ft = Number(/within (\d+) feet/.exec(html ?? '')?.[1] ?? NaN);
  return Number.isNaN(ft) ? null : ft <= 60 ? 'close' : ft <= 120 ? 'long' : 'extreme';
};

function role(d, traits, salvoReach) {
  const armyType = d.flags?.['pf2e-reignmaker']?.creatureData?.armyType;
  if (armyType === 'cavalry') return 'cavalry';
  if (traits.some((t) => ['giant', 'dragon', 'beast'].includes(t))) return 'monster';
  if (salvoReach && salvoReach !== 'close') return 'archers';
  if (salvoReach === 'close') return 'skirmisher';
  return 'infantry';
}

const cards = files.map((f) => {
  const d = JSON.parse(readFileSync(join(dir.pathname, f), 'utf8'));
  const s = d.system;
  const battle = d.items.find((it) => it.name.includes('[Battle]'));
  const salvo = d.items.find((it) => it.name.includes('[Salvo]'));
  const battleDc = dc(battle?.system.description.value);
  if (Number.isNaN(battleDc)) throw new Error(`${f}: no Battle DC`);
  const salvoDc = salvo ? dc(salvo.system.description.value) : NaN;
  const reach = salvo ? reachOf(salvo.system.description.value) : null;
  const traits = s.traits?.value ?? [];
  const fly = (s.attributes.speed.otherSpeeds ?? []).some((o) => o.type === 'fly');
  return {
    slug: f.replace(/\.json$/, ''),
    name: d.name,
    level: s.details.level.value,
    role: role(d, traits, reach),
    pace: fly || s.attributes.speed.value >= 30,
    fear: false,
    tactics: [],
    overrides: {
      strike: battleDc - 10,
      volley: salvo ? salvoDc - 10 : null,
      reach,
      defence: s.attributes.ac.value,
      will: s.saves.will.value,
      perception: s.perception?.mod ?? s.attributes.perception?.value ?? 0,
    },
  };
}).sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));

const body = cards.map((c) => {
  const o = c.overrides;
  const reach = o.reach ? `'${o.reach}'` : 'null';
  return `  { name: ${JSON.stringify(c.name)}, level: ${c.level}, role: '${c.role}', pace: ${c.pace}, fear: false, tactics: [], overrides: { strike: ${o.strike}, volley: ${o.volley}, reach: ${reach}, defence: ${o.defence}, will: ${o.will}, perception: ${o.perception} } },`;
}).join('\n');

writeFileSync(new URL('../src/engine/combatants.ts', import.meta.url),
`import type { UnitCard } from './cards.js';

// Generated by scripts/import-troops.mjs from data/troops/*.json. Edit the JSON, not this file.
export const COMBATANTS: UnitCard[] = [
${body}
];
`);
console.log(`${cards.length} combatants written`);
